version: '3'

services:
  app:
    build: .
    command: ["gunicorn", "--config", "gunicorn_config.py", "app:app"]
    expose:
      - "8080"
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
